title: BADMINTONCOACH WANTED
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.11299773119390011
  brandStrength: 0.06311606452800333
  rhythmicContrast: 0.4924015214201063
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  lightness: 0.9402295460458845
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
author:
  name: Diemo Ruhnow
  email: diemoruhnow@web.de
  url: 'http://www.badminton.training'
name: BADMINTONCOACH WANTED
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.541263768216595
layout_spectrum: 0.5078371246345341
