collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.8566231608856469
  brandStrength: 0.6455834051594138
  lightness: 0.6617191394325346
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  rhythmicContrast: 0.917303116992116
typography_spectrum: 0.20136853982694447
layout_spectrum: 0.5227814102545381
name: badmintoncoach
