collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.9960143333300948
color:
  brandStrength: 0.015464165015146136
  lightness: 0.9664975828491151
  saturation: 0.8495807056315243
  rhythmicContrast: 0.17268463992513716
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
layout_spectrum: 0.3484092829748988
name: badmintoncoach
