collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.7325865384191275
  brandStrength: 0.9175998631399125
  lightness: 0.32304806681349874
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  rhythmicContrast: 0.4064445795956999
typography_spectrum: 0.8156416954007
layout_spectrum: 0.5227814102545381
name: BADMINTONCOACH WANTED
