collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.4054779
  brandStrength: 0.01546416501514614
  lightness: 0.5537057
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  rhythmicContrast: 0.2475832
typography_spectrum: 0.9960143333300948
layout_spectrum: 0.6621912
name: badmintoncoach
