title: BADMINTONCOACH WANTED
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  brandColors:
    - '#E7E8D1'
    - '#D3CEAA'
    - '#FBF7E4'
    - '#424242'
    - '#8E001C'
  brandStrength: 0.698696888750419
  lightness: 0.2886474863626063
  saturation: 0.2858467230107635
  rhythmicContrast: 0.8268238501623273
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
name: BADMINTONCOACH WANTED
author:
  name: Diemo Ruhnow
  email: diemoruhnow@web.de
  url: 'http://www.badminton.training'
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.013241205830127
layout_spectrum: 0.5227814102545381
