title: BADMINTONCOACH WANTED
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.2858467
  brandStrength: 0
  lightness: 1
  brandColors:
    - '#E7E8D1'
    - '#D3CEAA'
    - '#FBF7E4'
    - '#424242'
    - '#8E001C'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: BADMINTONCOACH WANTED
author:
  name: Diemo Ruhnow
  email: diemoruhnow@web.de
  url: 'http://www.badminton.training'
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.013241205830127
layout_spectrum: 0.6686359
