name: BADMINTONCOACH WANTED
favicon: null
layout_spectrum: 0.5227814102545381
typography_spectrum: 0.8156416954007
author:
  name: Diemo Ruhnow
  email: diemoruhnow@web.de
  url: 'http://www.badminton.training'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: BADMINTONCOACH WANTED
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.9175998631399125
  lightness: 0.625
  saturation: 0.8125
  rhythmicContrast: 0.4064445795956999
purpose: []
